# Generated by Django 3.1.4 on 2021-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Hours worked for the day.', max_digits=5),
        ),
    ]
